/**
 * A full brrr request payload.
 *
 * This is a low-level brrr primitive.
 *
 * The memo key must be generated by the instantiator of this class, and it
 * must be deterministic: the "same" args and kwargs must always encode to the
 * same memo key.
 *
 * Using the same memo key, we store the task and its argv here so we can
 * retrieve them in workers.
 *
 * <docsync>Call</docsync>
 */
export interface Call {
  readonly taskName: string;
  readonly payload: Uint8Array;
  readonly callHash: string;
}
